# Generated by Django 3.0.3 on 2020-02-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=25, unique=True)),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('company_website', models.URLField(unique=True)),
                ('hq_city', models.CharField(max_length=80)),
                ('hq_country', models.CharField(max_length=80)),
                ('founded_date', models.DateField()),
                ('sector', models.CharField(blank=True, max_length=80)),
                ('last_funding_amount', models.FloatField()),
                ('total_funding_amount', models.FloatField()),
            ],
        ),
    ]
