# Generated by Django 3.0.3 on 2020-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_ups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='last_funding_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='total_funding_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
